# Google Drive Dataset Configuration
# Fill in the Google Drive file IDs or URLs for each dataset below
# 
# Supported formats:
# - Full URL: https://drive.google.com/file/d/FILE_ID/view?usp=sharing
# - Direct URL: https://drive.google.com/uc?id=FILE_ID
# - File ID only: FILE_ID
#
# Example:
#   file_id: "1a2b3c4d5e6f7g8h9i0j"
#   url: "https://drive.google.com/file/d/1a2b3c4d5e6f7g8h9i0j/view?usp=sharing"

datasets:
  patient_wise_mat:
    # Patient-wise MATLAB format dataset
    file_id: ""  # Replace with your Google Drive file ID or URL
    output_filename: "patient_wise_data.mat"  # Filename to save as
    enabled: true  # Set to false to skip this dataset
  
  csv_dataset:
    # CSV format dataset
    file_id: ""  # Replace with your Google Drive file ID or URL
    output_filename: "dataset.csv"  # Filename to save as
    enabled: true  # Set to false to skip this dataset
  
  delhi_hospital_mat:
    # Delhi hospital MATLAB format dataset
    file_id: ""  # Replace with your Google Drive file ID or URL
    output_filename: "delhi_hospital_data.mat"  # Filename to save as
    enabled: true  # Set to false to skip this dataset
